version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./tma/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./subdom-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_OWNER_ID=${TELEGRAM_OWNER_ID:-}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID:-}
      - DB_PATH=/app
    # ❌ УБИРАЕМ volumes — всё уже внутри контейнера
    networks:
      - app-network
    volumes:
      - ./subdom-server/nft-domains-mainnet.db:/app/nft-domains-mainnet.db
networks:
  app-network:
    driver: bridge
