FROM node:20-alpine

WORKDIR /app

#RUN apk add --no-cache python3 make g++

RUN apk add --no-cache python3 py3-setuptools make g++

COPY package*.json ./

RUN npm ci

COPY . .

COPY *.db /app/

# Создаем dist если его нет
RUN mkdir -p dist

# Проверяем и собираем
RUN if [ -f "src/server-sqlite.ts" ]; then \
    echo "Собираем TypeScript..."; \
    npm run build || echo "Сборка завершилась с ошибками"; \
    else \
    echo "Файл src/server-sqlite.ts не найден"; \
    echo "Доступные .ts файлы:"; \
    find src -name "*.ts"; \
    fi

RUN mkdir -p /app/db

EXPOSE 3000

# Запускаем через ts-node (надежнее)
CMD ["npx", "ts-node", "src/server-sqlite.ts"]
